### ISSUE TITLE
Inserção de item bibliografico

### ISSUE THREAD

**Issue by igorgallon** [igorgallon/DC-UFSCar-ES2-201601--GrupoAbeliano#1]
Na funcionalidade **Inserção de item bibliográfico** (BibTeX → New
entry), para as categorias book e article, realizar os seguintes
incrementos:
1. Validar os seguintes campos de acordo com as seguintes regras:
- Year: deve ser um ano válido (de acordo com o calendário da linguagem Java)
- Bibtexkey: definido pelo usuário ou automaticamente, deve ter no mínimo 2
  caracteres, sendo o primeiro uma letra maiúscula ou minúscula

**Comment by gabrielNT** [comment]
A validação de Year foi implementada no _branch_, verificando se o ano está num formato válido ou se ele não é maior que o ano atual - modificando a função _setField()_ em _BibEntry.java_. A segunda validação, de Bibtexkey, ainda deve ser feita.

**Comment by gabrielNT** [comment]
Funcionalidades foram implementadas e testadas, um merge request foi feito para o branch com as modificações.
