### ISSUE TITLE
Manutenção Importação de itens bibliograficos na base corrente

### ISSUE THREAD

**Issue by igorgallon** [igorgallon/DC-UFSCar-ES2-201601--GrupoAbeliano#2]
Na funcionalidade **Importação de itens bibliográficos na base
corrente** (File → Import into current database), realizar os seguintes
incrementos:
- Oferecer a opção de importar arquivo em formato CSV
- Oferecer a opção de criação de um novo arquivo (database) quando existirem
  entradas duplicadas no arquivo corrente (current database) e o arquivo que está
  sendo importado (considerar formatos BibTeX e CSV).

**Comment by alex-dias** [comment]
Foi criado um branch para implementar a funcionalidade de importação da extensão CSV.
Um novo branch será criado para solucionar o problema de duplicadas.

**Comment by vitox761** [comment]
A implementação para da classe para importar arquivos .csv esta completa.

**Comment by vitox761** [comment]
A implementação do tratamento de duplicatas esta completa.
